# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/amc/opt/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/amc/opt/clion/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amc/git/libswoc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amc/git/libswoc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/amc/opt/clion/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amc/git/libswoc/CMakeFiles /home/amc/git/libswoc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amc/git/libswoc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libswoc

# Build rule for target.
libswoc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libswoc
.PHONY : libswoc

# fast build rule for target.
libswoc/fast:
	$(MAKE) $(MAKESILENT) -f code/CMakeFiles/libswoc.dir/build.make code/CMakeFiles/libswoc.dir/build
.PHONY : libswoc/fast

#=============================================================================
# Target rules for targets named test_libswoc

# Build rule for target.
test_libswoc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_libswoc
.PHONY : test_libswoc

# fast build rule for target.
test_libswoc/fast:
	$(MAKE) $(MAKESILENT) -f unit_tests/CMakeFiles/test_libswoc.dir/build.make unit_tests/CMakeFiles/test_libswoc.dir/build
.PHONY : test_libswoc/fast

#=============================================================================
# Target rules for targets named ex_netdb

# Build rule for target.
ex_netdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex_netdb
.PHONY : ex_netdb

# fast build rule for target.
ex_netdb/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/ex_netdb.dir/build.make example/CMakeFiles/ex_netdb.dir/build
.PHONY : ex_netdb/fast

#=============================================================================
# Target rules for targets named ex_netcompact

# Build rule for target.
ex_netcompact: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex_netcompact
.PHONY : ex_netcompact

# fast build rule for target.
ex_netcompact/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/ex_netcompact.dir/build.make example/CMakeFiles/ex_netcompact.dir/build
.PHONY : ex_netcompact/fast

#=============================================================================
# Target rules for targets named ex_flat_space

# Build rule for target.
ex_flat_space: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex_flat_space
.PHONY : ex_flat_space

# fast build rule for target.
ex_flat_space/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/ex_flat_space.dir/build.make example/CMakeFiles/ex_flat_space.dir/build
.PHONY : ex_flat_space/fast

#=============================================================================
# Target rules for targets named ex_diskstats

# Build rule for target.
ex_diskstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex_diskstats
.PHONY : ex_diskstats

# fast build rule for target.
ex_diskstats/fast:
	$(MAKE) $(MAKESILENT) -f example/CMakeFiles/ex_diskstats.dir/build.make example/CMakeFiles/ex_diskstats.dir/build
.PHONY : ex_diskstats/fast

#=============================================================================
# Target rules for targets named documentation

# Build rule for target.
documentation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 documentation
.PHONY : documentation

# fast build rule for target.
documentation/fast:
	$(MAKE) $(MAKESILENT) -f doc/CMakeFiles/documentation.dir/build.make doc/CMakeFiles/documentation.dir/build
.PHONY : documentation/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... documentation"
	@echo "... ex_diskstats"
	@echo "... ex_flat_space"
	@echo "... ex_netcompact"
	@echo "... ex_netdb"
	@echo "... libswoc"
	@echo "... test_libswoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

